### ISSUE TITLE
Make sure currentStatus is set on integrations

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis-rest#277]
A few integrations don't have `currentStatus` set, and some do, the `currentStatus` field should be set on each integration.

As a workaround in the UI we're actually just showing `desiredStatus`, but I'd like to fix this => https://github.com/redhat-ipaas/ipaas-ui/issues/384

**Comment by kahboom** [comment]
+1 This is a big deal, as we are planning on tracking "in progress" states (ie integrations in the process of being activated/deactivated), where integrations may be transitional and cannot be deleted or activated, etc. We also check both status types for different reasons, including discrepancies between them to determine whether or not to display certain things.

**Comment by KurtStam** [comment]
This has to do with the [workflow](https://github.com/KurtStam/ipaas-rest/tree/master/docs/workflows) setting the status, which is what @iocanel is working on. Th example integrations have this field set just so that you the UI can display something. 

I'm currently setting the initial state to 'Draft' when the integration is first created (POST).

**Comment by kahboom** [comment]
@KurtStam - Since @iocanel 's PR was merged do we have `currentStatus` being updated properly? We would need it to be set properly once integrations are created, and we can then set `desiredStatus` ourselves, check for discrepancies to determine an 'In Progress' state, etc.

**Comment by KurtStam** [comment]
@kahboom I think it now is hooked up. It should follow the stati as described in the workflow diagrams:
https://github.com/KurtStam/ipaas-rest/tree/master/docs/workflows. Maybe want to double check with @iocanel

**Comment by gashcrumb** [comment]
BTW, the `Twitter to Salesforce Example` integration doesn't return a currentStatus.  Also with my code in the linked PR all the integrations just show spinners since `currentStatus` != `desiredStatus.

**Comment by kahboom** [comment]
>BTW, the Twitter to Salesforce Example integration doesn't return a currentStatus. Also with my code in the linked PR all the integrations just show spinners since currentStatus != `desiredStatus.

Yesterday all but Activated integrations were returning a currentStatus. Activated did not show a currentStatus. I wonder if it's related?

**Comment by kahboom** [comment]
I'd need to confirm that though, not sure there is a direct correlation but one or two were definitely not even returning that property at all.

**Comment by rhuss** [comment]
I just updated deployment.json it with #316 so I set the current and desired status to "Activated" for now. Will be available as soon as this PR is merged.

**Comment by rhuss** [comment]
It's here https://github.com/redhat-ipaas/ipaas-rest/pull/316/files#diff-601dc197aef7766f6b54737b28037f14

**Comment by kahboom** [comment]
@rhuss - This should take care of the issue where 'Activated' Integrations are the only ones that do not appear to return a `currentStatus`, correct? If not, @KurtStam , we'd need to set that for the example data.

[Here](https://gist.github.com/kahboom/972d630e3f0c79b4dfc80e712715fbf4#file-integrations-json-L93) is a Gist of what I get back for `/v1/integrations`, specifically linking to one integration that is missing the `currentStatus`, presumably because it is active? [Here](https://gist.github.com/kahboom/972d630e3f0c79b4dfc80e712715fbf4#file-integrations-json-L248) is an integration that includes both. I only assume it's happening to active integrations because I don't ever see an Activated or Active `currentStatus` for an integration.

As a result, you can see in my screenshot here that active Integrations are not being counted in the Dashboard and do not return a label, as that is dependent on `currentStatus`:

<img width="1440" alt="screen shot 2017-04-19 at 10 38 32 pm" src="https://cloud.githubusercontent.com/assets/3844502/25211315/b33f38d8-2552-11e7-9b3d-a292fedee3ec.png">

**Comment by rhuss** [comment]
@kahboom It is expected that **all** integrations always carry a _currentStatus_ and a _desiredStatus_. When both are not equally then integration is in progress, still trying to reach the the desired state. We still have to think about error states, but that's  a different story.

I hope I can merge my PR today (when the reviewers have mercy with me ;-) so that this is fixed.

We have currently still some issues to reach the _Activated_ state for new integration. Currently they will eventually be stuck in _Pending_. (For the real mode, there is also a demo mode which goes from _Draft_ -> _Pending_ -> _Activated_ with a 5s delay between each).

**Comment by iocanel** [comment]
@rhuss pull request has been now merged.
Can we close this now? @kahboom ? @gashcrumb ?

**Comment by kahboom** [comment]
Thanks @rhuss - sorry, had not seen your response. That last issue with _Draft -> Pending -> Activated_ is a real bummer, but hopefully we'll be able to resolve that soon.

@iocanel Yep with @rhuss 's PR merged in I think this is good to close. 👍  Thank you both!
