### ISSUE TITLE
REST apis must not send credentials back to the client

### ISSUE THREAD

**Issue by chirino** [syndesisio/syndesis-rest#373]
I think it might be a good idea if the REST apis which set and get sensitive data was structured so you can only set those sensitive properties but never get them back via the REST apis.

**Comment by chirino** [comment]
We also might need to consider encrypting these values while they are at rest in the DB.

**Comment by gashcrumb** [comment]
Not sure that this would currently affect the UI really except with the connection configuration, even then we don't really need to fetch it.  That connection object gets embedded in the integration object, but again the UI doesn't really need to pass along secrets in that case either...

**Comment by dsimansk** [comment]
I wonder what is conceptually different between storing Secrets as OpenShift resource where you can still retrieve them and storing our Connection secret. In my opinion there should be still an user with appropriate role that can retrieve that credential. Maybe those credentials shouldn't be exposed directly on Connection GET query, but nested/hidden(a bit)?

**Comment by jimmidyson** [comment]
This looks like we might want to think about having different types for properties: something like `Value` and `SecretValue`, where `SecretValue` is a reference to a secret (another type in DB, possibly encrypted) value rather than stored in the `Connection` object in the DB. Then when we're serializing in the GET `Connection` a `SecretValue` would serialize as a fixed string, like `********` or something.

**Comment by chirino** [comment]
We already know which properties are [sensitive](https://github.com/syndesisio/syndesis-rest/blob/master/model/src/main/java/io/syndesis/model/connection/ConfigurationProperty.java#L33).  Can't we just use that?

**Comment by jimmidyson** [comment]
I feel that if something is sensitive then it should be more explicit when requesting to view it. That way we could start to introduce some more permission levels in future.

I also would prefer the fact that something is sensitive to be stored with the data, rather than just a raw String->String map and having to read back from the relevant ConfigurationProperty if it's meant to be sensitve/encrypted.

**Comment by chirino** [comment]
@jimmidyson I think that would have ui impact right @gashcrumb?  The UI cant assume the values are Strings, you might get an object in there for the secret fields.

**Comment by gashcrumb** [comment]
Yeah, most likely.

**Comment by KurtStam** [comment]
@chirino is this still an issue? There have been quite a few commits related to this. Do you know the current status?

**Comment by chirino** [comment]
I've not checked.

**Comment by rhuss** [comment]
Yes, it's still an issue.

**Comment by chirino** [comment]
So this is mostly fixed now, except for the secret configured for the simpledb connector that the DB is initialized with.
