### ISSUE TITLE
stepKind not correct for Basic Filter

### ISSUE THREAD

**Issue by kahboom** [syndesisio/syndesis-rest#451]
lol I don't know if selected the correct labels for this issue, but all seemed appropriate...

Reaching a 500 internal server error when trying to save an integration with the basic filter `configuredProperties`. See screenshots below.

Upon closer inspection of the [filter proposal](https://github.com/syndesisio/syndesis-project/blob/master/proposals/002-filter-data.md#domain), my best guess is that the `stepKind` has not been updated to be `basic-filter`. We have reserved the `stepKind` of `filter` for the advanced filter and `basic-filter` for the basic filter. Please note that we cannot use the same `stepKind` for both basic and advanced filters, as this property is used to determine which view to render.

<img width="1680" alt="screenshot 2017-07-20 22 30 36" src="https://user-images.githubusercontent.com/3844502/28447588-9d370fd0-6d9f-11e7-9b86-b0a1ef104e55.png">
<img width="1680" alt="screenshot 2017-07-20 22 31 35" src="https://user-images.githubusercontent.com/3844502/28447591-9ebe863a-6d9f-11e7-8205-a4a49008afcc.png">
<img width="1680" alt="screenshot 2017-07-20 22 32 53" src="https://user-images.githubusercontent.com/3844502/28447595-a251e134-6d9f-11e7-8636-609f2e53290c.png">
<img width="1679" alt="screenshot 2017-07-20 22 35 26" src="https://user-images.githubusercontent.com/3844502/28447596-a4d06cfa-6d9f-11e7-9f6a-fded700b66e7.png">
<img width="1083" alt="screenshot 2017-07-20 22 36 19" src="https://user-images.githubusercontent.com/3844502/28447600-a88313e8-6d9f-11e7-8144-b8822eac0890.png">

**Comment by jimmidyson** [comment]
There shouldn't be a new step kind imo, as the proposal states. This is just a configured filter, either with `simple` field populated for basic filter or `rules` populated for advanced filters.

The view to render needs to be derived from these property values. Technically why can't that happen?

Fyi this shouldn't return a 500, but a 422 (unprocessable entity) with the appropriate validation error message to the client.

**Comment by gashcrumb** [comment]
We don't have code in place to interpret what's in configured properties
when you pick a step, it's doable I guess but then you can't roundtrip
between the two views anyways.  So then they feel like two totally
different things.

**Comment by jimmidyson** [comment]
Hmm. I think in future it makes sense for steps to be properly typed, as in not just using `confgurationProperties` as a property bucket, but rather have e.g. `filter` have properties `rules` and `simple` instead. Thoughts @rhuss? I understand the need for configuration properties for connections but steps should be easier to strongly type I think.

In the meantime... I wonder what the best option is to do right now for this demo. As @rhuss said somewhere, do we have a working advanced filter? If not, then can we just use `filter` stepKind as the basic filter for now?

**Comment by gashcrumb** [comment]
The Twitter to Salesforce example integration there uses the advanced
filter currently, so that change would break that one.

**Comment by jimmidyson** [comment]
:disappointed:

**Comment by gashcrumb** [comment]
Also, having it typed the way you propose makes it more difficult to dig
form config out of the step, not a problem for a custom interface like the
basic filter though.  I guess if the plan is to have more of these kind of
interface then sure, but if most steps are going to use the form builder
then meh.

**Comment by gashcrumb** [comment]
One more thought and then I'm done, promise!  Steps are currently defined on the client.  If we type em then we should be defining em at the backend I feel.

**Comment by jimmidyson** [comment]
I totally agree that steps should be defined in the REST API, yes. A strongly-typed API is always my personal preference.

**Comment by kahboom** [comment]
So, are we changing the `stepKind` in the API or trying some type of workaround in the UI?

**Comment by rhuss** [comment]
I like to have a more typed interface for different _kind_ of steps, so stuffing stuff all in an opaque properties object is not optimal. 

I also agree with @gashcrumb that the step objects should be distinguishable by a single datum to make it easier in the UI to select how to render them without doing a deep inspection (and already knowing about the step format at that level in the UI).

What do you think about using different stepKinds for the advanced and basic filter (as initially suggested) but add a 'category' filter for both?

The API should be able to handle steps individually and not only as part of an integration. In general, the API to syndesis-ui should it make as easy as possible for the UI to work with objects without too heavy domain object gymnastics. This should be shielded from the UI to not unnecessarily couple the UI to the domain / persistence business. I generally favour the mantra that an API 'must be easy to use, but might be hard to implement' and move as much burden to the backend side as possible.

**Comment by jimmidyson** [comment]
> I also agree with [@gashcrumb](https://github.com/gashcrumb) that the step objects should be distinguishable by a single datum to make it easier in the UI to select how to render them without doing a deep inspection (and already knowing about the step format at that level in the UI).

While I agree that makes things simpler for the UI, I'm a bit concerned that it potentially bloats the API model in future if we're unable to do slightly more granular inspection (in this case check on the presence of one top level property when the filter is properly typed rather than using an untyped property map), but I'm not going to argue about it too much :)

**Comment by kahboom** [comment]
>What do you think about using different stepKinds for the advanced and basic filter (as initially suggested) but add a 'category' filter for both?

I like this idea.

>In general, the API to syndesis-ui should it make as easy as possible for the UI to work with objects without too heavy domain object gymnastics. This should be shielded from the UI to not unnecessarily couple the UI to the domain / persistence business. I generally favour the mantra that an API 'must be easy to use, but might be hard to implement' and move as much burden to the backend side as possible.

+1

> I'm a bit concerned that it potentially bloats the API model in future if we're unable to do slightly more granular inspection

It's a lot easier to bloat the UI than it is to bloat an API model imo, especially considering that we store a lot of things in memory at the moment. Even if that were to change, the API generally can be broken up more easily without affecting the user experience, rather than the other way around, but of course am open to whatever you guys decide.

**Comment by kahboom** [comment]
Just let me know so I can update the UI.

**Comment by rhuss** [comment]
sorry, won't it make today anymore. will dive into it tomorrow

**Comment by kahboom** [comment]
No rush at all @rhuss , there are plenty other tasks I need to focus on. 👍

**Comment by rhuss** [comment]
> Also, having it typed the way you propose makes it harder to dig
> form config out of the step, not a problem for a custom interface like the
> basic filter though.  I guess if the plan is to have more of this kind of
> interface then sure, but if most steps are going to use the form builder
> then meh.

Ok, whats about the following suggestion for the Step model: We use a `stepKind` for every particular step so that it can be dispatched quickly on the UI. We use specific field keys for pages where we know we need them. We use `configuredProperties` (or maybe even only `properties` ?) as a free form map for use with the form-builder:

```yaml
steps:
- stepKind: endpoint
   connection: { ... }
   action: { ... }
- stepKind: log
   message: Bla
- stepKind: ruleFilter
   predicate:  AND
   rules:
   - path: body.text
      op: contains
      value: antman
   - path: header.kind
      op: "=~"
      value: "DC Comics"
- stepKind: expressionFilter
   expression: "${in.header.region} contains \"asia\" || ${body} regex \"bat(wo)?man\""
- stepKind: storeData
   data:
   - myFreeFormKey1: value1
   - myOtherFreeFormKey2: value2
```

Actually, if this is not to big a change, I would move from `stepKind` to `kind` (and instead of `configuredProperty` maybe `data` for steps with untyped information).

@gashcrumb does this fit into the UI way of using the steps ? We could also add another property like "category: step" or "category: connection" so that you can easily filter out endpoint and non-enpoints (as they seem to be treated differently in the UI, too)

@jimmidyson wdyt about this a-bit-better-typed approach ?

**Comment by jimmidyson** [comment]
Looks good to me but from what @gashcrumb said I don't think this will work for the current form builder way of doing things.

_Sent from my Samsung SM-G920F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by gashcrumb** [comment]
Yeah, I'd be fine with moving `stepKind` to `kind`.

Currently we keep the `properties` and `configuredProperties` as separate entities, i.e. `properties` is the form configuration and `configuredProperties` is purely the values produced by the form.  The `properties` attribute follows a JSON schema like pattern, whereas `configuredProperties` is fairly open ended.  I would suggest leaving these members in place as-is for the time being otherwise we'll have a big refactor task on our hands.

So top-level of the object is metadata (name, id icon etc) then `properties` and `configuredProperties` have the schema and the user supplied values.

I mean, we can change this, but again that has a big impact on the existing code and I'd definitely want to be doing it for a good reason, you know?

**Comment by rhuss** [comment]
@gashcrumb completely agreed not to change things now just for consistencies sake but breaking tons of other stuff. It was just my ignorance ;-)

But I wonder about the  whether the form builder would be ok with such a mixed model as described above in the example, as I assume that the form builder only applies to the stepKinds which support an opaque `configuredProperties` ?

[note: I updated the example above and revert back to `configuredProperties`]

**Comment by gashcrumb** [comment]
Yeah, so the basic filter page is a custom view, that stepKind can be totally different.  

At the moment the 'advanced filter' has a stepKind `filter` and it uses it's form config in 'properties' to create a text area.  We can change that to a custom view as well if we want or leave it as is, though if we go with the latter choice then the config needs to be like:

```
properties {
   expression: {
      type: 'textarea',   <----- could actually use some other indicator here to choose a better text editor
   }
}
```

which would produce a configuredProperties object like:


```
configuredProperties: {
   expression: "value here"
}
```

I don't know though, to be honest I don't think I like the specific step properties up at the root of the object where the name, icon etc is in your example.  Feels like they should be a bit separated.

**Comment by rhuss** [comment]
@gashcrumb Ok I see the point that that the 'expressionFilter' (as contrast to the 'ruleFilter') should issue the `configuredProperties` as it's build as a regular form (just wondering whether choosing a dedictated code editor doesn't make it already a candidate for a specialised page, eg. when you want to add a 'validate' button or so), but I'm fine wrapping the expression into it. 

For a regular step I don't see much ui info on the top-level (no icon btw, which I see only on connections), at it would make it feels more typesafe for this specific step as we can easier validate it (we leave 'configuredProperties' as a typeless map which cannot really be validated wrt to possible keys etc.). Actually, I would instead move the ui relevant parts into an extra section, e.g. 'annotations' (you see, I'm on the way to transform it to a kubernetes resource in disguise :), if there is any.

Also we need to add on the fly some data in the backend to the step (e.g. for the `ruleFilter` we are going to calculate the expression when saving, so its easier to consume by the runtime builder).

But I think this is a good compromise for now, so I'm going to implement the way we discussed (tomorrow hopefully ;). Will leave the other steps (like 'log') untouched for now.

[again updated the example above]

**Comment by gashcrumb** [comment]
@rhuss yep, that sounds good!

I think at the moment the step names are coming out of the controller now that I think about it, so you're right, not much UI metadata at the top-level.

I figure at the moment there's the summit example integration that still uses the 'filter' step as it is and I didn't want to break it.

**Comment by gashcrumb** [comment]
Linked PR changes the `stepKind` to `rule-filter`.  Returns a 500 when I try and update the current integration.  I see a couple problems though, some of them are ones I created when I hacked in the step store :-)

Steps need to have a separate name field and it'd be nice if these were somehow persisted, i.e. if we could rely on them coming back in the integration object.  It does for connections/actions for example.  Right now I've got lots of hacky code either converting the `stepKind` to something displayable or some quick and dirty switch cases for the ones that wouldn't display nicely regardless.

Also I realize that if we go and change `stepKind` to `kind`, it's gotta be done in all the example integrations *and* it's actually a pretty big impact to the UI, as we check for that everywhere.  So definitely need a heads up when/if that changes.

**Comment by rhuss** [comment]
I'm fine with leaving `stepKind` as it is (the `kind` would be `Step` anyway, so its much cleaner). 

I will have a look at the 500 tomorrow.

Persisting a name shouldn't be hard. Will add this tomorrow, too.

**Comment by gashcrumb** [comment]
@rhuss cool.  I also have a concern about moving the settings for the step outside of the `configuredProperties` attribute.  The UI kinda treats that as the untyped bucket of settings as we don't have full type information for all the different steps, so for example currently we're putting the configuration that the user generates on the basic filter page into configuredProperties.  If we have these at the root of the object, we don't currently have a good way to generate interfaces for frontend development.  And then our code starts becoming a mess of `if (step['some-attr'] || step['some-old-attr;])` kind of stuff which I'd love to avoid, or we have to hand-code interfaces which will break with any backend change at runtime.

**Comment by rhuss** [comment]
But isn't the rulte-filter step itself a very custom one which needs special interpretation anyway ? As I understood it was only for the generic form builder where `configuredProperties` is important, and it also assumes that the `configuredProperties` has a certain structure (e.g. a plain key-value map). 

For the basic filter we need a more complex structure (key-value map, where value can be a string (for "predicate") or a list of maps (for "rules").

Could you give a quick pointer into the UI code, where the dispatch happens ? (i know you already did, but I lost the bookmark ...)

**Comment by gashcrumb** [comment]
Am on PTO today, but lemme point you to the relevant bits in the UI code.  Here's the point where we figure out if a custom UI should be used:

https://github.com/syndesisio/syndesis-ui/blob/master/src/app/integrations/edit-page/step-configure/step-configure.component.ts#L137-L141

The basic filter page produces this config object:

https://github.com/syndesisio/syndesis-ui/blob/master/src/app/integrations/edit-page/step-configure/filter-steps/basic-filter.component.ts#L87-L91

When the user clicks next/done we set the configuredProperties object on the integration this way:

https://github.com/syndesisio/syndesis-ui/blob/master/src/app/integrations/edit-page/step-configure/step-configure.component.ts#L79-L91

The last bit is handled in a fairly generic way.  If we have other properties that need to be set on the step this all gets more complicated, at least, that's my concern.  I mean, I can redo all this code too, I like to be sure I understand the benefit though, you know?  I'm still not sure why we've diverged in calling the stepKind `rule-filter` vs "basic filter" as shown in the UI but...

**Comment by rhuss** [comment]
Thanks ! I will dive into tomorrow morning, so when you get up, everything should be prepared ;-)

enjoy your pto today ...

**Comment by rhuss** [comment]
After digging in the code, I understand your concerns. Although it might look be more concise to have a type interface on Step level (from API pov), actually its the `configuredProperties` map which is moved around in the UI and store generically in a steps `configuredProperties` field regardless of the form (e.g. whether its an individual part or not). 

Let's stay with the current approach so that we put everything into `configuredProperties` for now. If we do so, I wonder why this special handling in https://github.com/syndesisio/syndesis-ui/blob/master/src/app/integrations/edit-page/step-configure/step-configure.component.ts#L137-L141 is then required ? This couples the basic step-configure.component to a specific step (BasicFilter) which is not good. Maybe we can rename this to 'customProperties' or so ? And then instead of checking twice for BASIC_FILTER in a switch have a method 'isCustomForm()' ? Then custom forms can create their own configuredProperties format.

Let me prepare a PR which also fixes the issue with the custom options (but there is still more todo).

The reasoning for a more typed approach is that it can be easier verifier on the server side as it is mapped to type Java objects. The change would be to move away from generically updating a 'configuredProperties' to update a 'Step' where the default action would be to update the step's configuredProperties (but a custom view could overwrite this and update other parts of the step, too). So instead of switches in the base class maybe polymorphic inheritance might be more elegant and extensible ?


> I'm still not sure why we've diverged in calling the stepKind rule-filter vs "basic filter" as shown in the UI but...

The reasoning between this rename was a pure semantic one: 'basic' filter has not really a meaning (as 'small filter', 'simple filter', 'easy filter', ...) whereas I thought 'rule-filter' already implies by its name that is consists of a list of 'rules'. (same reasoning why I'd like to talk about an 'expression-filter' instead of an 'advanced-filter'). But I'm fine with reverting this to 'basic filter' as it might fit better the UI (where, tbh, I would also prefer a more expressive name like 'Rule Filter').

----

After all, it also can be that this does not make much sense, as I just started to look into the UI (my apologies) and even to Angular 4.

**Comment by gashcrumb** [comment]
Yep, we've adopted `rule-filter` so that doesn't need to change.  And yes, I think that coupling you've pointed out needs to change as well, I think your suggested approach would be good, am slowly trying to refactor stuff like this post-summit without breaking everything :-)

**Comment by rhuss** [comment]
@gashcrumb while reverting the API there is the problem that `configuredProperties` is  `Map<String,String>` on the server side. which is not suitable for the complex structure of basic filters which have a list of rules.  So all we could do now is to put a single key 'rules' into configuredProperties which then contains a stringified JSON object as value.

Of course this is not nice from an API point of view, but would this help for now ?

**Comment by rhuss** [comment]
[Here](https://github.com/rhuss/syndesis-ui/blob/eaa6758bff1678fdbffd0ac54a802b49fc8539f4/src/app/integrations/edit-page/current-flow.service.ts#L331) the `step.configuredProperties` is set to an arbitrary JSON object. However, this works *only* when these properties are a strict string-string map (otherwise deserialization in the backend fails, as it is based on an object mapper). 

For the basic filter this is however a complex object `BasicFilter` with an inner structure (like a list of rules).

I see currently three solutions:

1. Keep the typed interface we have right now (with the top-level elements)
2. Try to fix the backend to allow e.g. a JSONObject for configuredProperties (and change all places in the backend accordingly)
3. Mangle configuredProperties here to fit to a Map<String,String> schema, which means converting any non-string value to a json-string.

I think that 

1. would be the most elegant but would need the most UI work
2. could be possible, but I don't know and requires some backend work (but no UI work)
3. would be the fastest but also the ugliest.

@gashcrumb @jimmidyson @zregvart Wdyt ? I'd like to resolve this quickly so that we don't risk the demo on Friday.

**Comment by gashcrumb** [comment]
damn!  Let's do option 3 and then figure out a long-term solution to this...  Ideally I'd love to have proper types available to the frontend code as well so we can hit changes at compile time.

**Comment by jimmidyson** [comment]
I agree with 3 for now, to get this demo tight, we can revisit when we can.

**Comment by rhuss** [comment]
ok @gascrumb, could you build this conversion to a plain string for the valus to https://github.com/rhuss/syndesis-ui/blob/eaa6758bff1678fdbffd0ac54a802b49fc8539f4/src/app/integrations/edit-page/current-flow.service.ts#L331 ? I would do the reverse code then on the backend side.

**Comment by rhuss** [comment]
and here, too: https://github.com/rhuss/syndesis-ui/blob/eaa6758bff1678fdbffd0ac54a802b49fc8539f4/src/app/integrations/edit-page/current-flow.service.ts#L370

**Comment by rhuss** [comment]
to be clear, the backend now expects a `configuredProperties` map of the following form:

```json
{
    "predicate" : "and",
    "rules": "[ { 'path': 'body.text', 'op': 'contains', 'value: 'bla' }, { 'path': 'body.nr', 'op': '>=', 'value': '10' }]"
}
```

No 'type' or 'simple' is required for `BasicFilter`, but `op` should be mandatory in `Rule` (in filter.interface.ts).

@gashcrumb I could give it a try for the UI if you like (and if you are busy with other tasks).

**Comment by gashcrumb** [comment]
@rhuss of you don't mind that'd be awesome, still tied up with oauth.  I'd be happy to review...

**Comment by rhuss** [comment]
ok, so I will take that.

**Comment by gashcrumb** [comment]
@rhuss let me hack that in real quick now, I've a minute...

**Comment by gashcrumb** [comment]
Done, this is what's being sent now when you create a basic filter step:

```json
 {
      "stepKind": "rule-filter",
      "configuredProperties": {
        "type": "rule",
        "predicate": "AND",
        "rules": "[{\"path\":\"foo\",\"op\":\"contains\",\"value\":\"bar\"},{\"path\":\"bar\",\"op\":\"contains\",\"value\":\"foo\"}]"
      }
    },
```

**Comment by rhuss** [comment]
Thanks ! We can ommit the 'type: rule' as this is redundant. 'predicate' and 'rules' is enough.

**Comment by rhuss** [comment]
@gashcrumb Actually it doesn't yet work as the form builder requires a structure json object to set inner fields for the rule rows. So the conversion must happen on initialisation of the component and when the configuredProperties are saved back (not [here](https://github.com/syndesisio/syndesis-ui/pull/756/files/6ba05dd5fc81fba5cbbd2d5e4d59168f25c39886#diff-08bb34b7a3addabf51df650344921d4fR115)). 

Unfotunately I'm such an Angular 4 noob that I just downloaded a tutorial ;-), but I have still no idea where this initialisation and write back happens.

@gashcrumb could you have a look please ?

**Comment by gashcrumb** [comment]
I think we can close this one now that it's working...
