### ISSUE TITLE
Precompute atlasmap inspections at build time and provide a service for them

### ISSUE THREAD

**Issue by chirino** [syndesisio/syndesis-rest#466]
Atlasmap now has a maven-plugin that can generate the inspections at build time.
Use that to precompute all the inspections and create a rest service that the UI can use to access those precomputed values.

**Comment by rhuss** [comment]
Maybe we could add this to syndesis-verifier as this has already all dependencies to the connectors we support ? We could rebrand syndesis-verifier to syndesis-connector-service (or syndesis-connector) for handling connector related logic (and syndesis-rest could cache the meta data).

btw, having the verifier as an extra service (instead of including it directly within syndesis-rest) has the big benefit that it decouples communication to the connector backends (for parameter validation) from the other logic, so that if this breaks it only breaks the connection validation, not the whole app.

------

But thinking again, its probably easier to put the mappings directly into the connectors (in syndesis-connectors) and use a `compile` scope deps for those connectors here in syndesis-rest and a mini plugin to extract only those descriptors to put it into syndesis-rest as resources. So we can avoid having runtime deps on the connectors for syndesis-rest (but still compile time deps which we could avoid with the former approach).

-------

We can also skip putting the descriptors into the connectors and create them with the plugin directly here in syndesis-rest, too. 'guess this was your original suggestion ;-)

**Comment by zregvart** [comment]
Does the dynamic nature of Salesforce influence this? The number of objects and their structure can be only known at runtime with Salesforce.

**Comment by rhuss** [comment]
It's probably only for the static, java based introspection. This is also the most expensive one as it currently spins up a Maven build as an external process. 

Not sure how the integration with the JSON schema based mapper works yet.

**Comment by chirino** [comment]
Right.  Was thinking since it's just a build time dep (they wont even show up in the scopes) that generating some resource files in the rest module should work.
