### ISSUE TITLE
Full list of enum property potential values isn't returned when a configuration value has been previously set

### ISSUE THREAD

**Issue by gashcrumb** [syndesisio/syndesis-rest#599]
Noticed this when sticking in the typeahead support.  If I configure the salesforce create/update to use an object, add it to my integration and then go back into the configuration, the `enum` property in the form only contains the item that I had configured, none of the other values that are present that were there when first creating the connection.

Same goes for the unique ID field.

Note, requires https://github.com/syndesisio/syndesis-ui/pull/955 to really be able to see it

Related to https://github.com/syndesisio/syndesis-ui/issues/949

**Comment by gashcrumb** [comment]
@zregvart FYI

**Comment by zregvart** [comment]
The issue is that in we use two different Salesforce REST endpoints to gather metadata that results in input/output data shapes or enum's of properties being populated: one to fetch a list of all objects, and another to fetch details of a specific object. The Camel metadata extension for Salesforce uses `sObjectName` property to determine which endpoint to invoke. When `sObjectName` is defined the extension looks at specific object defintion and we can get only those details, like fields of an object or input/output data shapes, and correspondingly when it is not defined we can get the list of Salesforce objects.

**Comment by zregvart** [comment]
Seems to me a good way to accomplish that is by adding additional logic in [adapters](https://github.com/syndesisio/syndesis-verifier/blob/5152fbc271588dea6b58fce568ded3e655107430/src/main/java/io/syndesis/verifier/v1/metadata/MetadataAdapter.java) in _verifier_

cc @KurtStam

**Comment by zregvart** [comment]
Of course on quick way of fixing this would be to make the UI send only values from the steps up to the current step, e.g. empty JSON on the first step even if the user has chosen action property values.

Given our assumption (rule?) that the action properties that depend on another action property will only be presented at the next step this would hold true in general.
